# Generated by Django 4.0.2 on 2023-08-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_file_remove_post_files_post_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
