# Generated by Django 4.0.2 on 2023-07-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stu_id', models.IntegerField(verbose_name='학번')),
                ('first_name', models.CharField(max_length=30, verbose_name='성')),
                ('last_name', models.CharField(max_length=30, verbose_name='이름')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
